### ISSUE TITLE
Request for Guidance on Achieving Data Files in Specific R Markdown Scripts

### ISSUE THREAD

**Issue by drhchen** [stefanogg/staph_adaptation_paper#6]
How can I achieve the "df_FPR3757_functional_annotation_amr_plus.Rda" located in GSEA_ontologies_analysis.Rmd and the "df_neb_curated.Rda" located in Combined_annotation.Rmd?

**Comment by stefanogg** [comment]
Files added to the repository (commit 8934033bf09b665f247489d123ff8077b4be6bba)
